apiVersion: vmware.com/v1alpha1
kind: Sidecar
metadata:
  name: telegraf
spec:
  containers:
    - name: telegraf
      image: telegraf:1.13.4-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
      env:
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy.default
        - name: WAVEFRONT_PROXY_PORT
          value: "2878"
        - name: INTERVAL
          value: 30s
        - name: CLUSTER
          value: "prod"
        - name: PREFIX
          value: "linkerd_"
        - name: METRIC_SOURCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['k8sapp']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      resources:
        requests:
          memory: 30Mi
          cpu: 100m
        limits:
          memory: 50Mi
          cpu: 200m
